/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  sym__inline_tag_false_positive = 3,
  sym_tag_name_with_argument = 4,
  sym_tag_name_with_type = 5,
  sym_tag_name = 6,
  anon_sym_COLON = 7,
  anon_sym_SLASH = 8,
  anon_sym_DOT = 9,
  anon_sym_POUND = 10,
  anon_sym_TILDE = 11,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 12,
  sym_code_block_language = 13,
  sym_code_block_line = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  sym_identifier = 17,
  sym__text = 18,
  anon_sym_SLASH2 = 19,
  anon_sym_STAR = 20,
  sym_type = 21,
  sym_document = 22,
  sym_description = 23,
  sym_tag = 24,
  sym_inline_tag = 25,
  sym__expression = 26,
  sym_qualified_expression = 27,
  sym_path_expression = 28,
  sym_member_expression = 29,
  sym_code_block = 30,
  sym_optional_identifier = 31,
  sym__begin = 32,
  sym__end = 33,
  aux_sym_document_repeat1 = 34,
  aux_sym_description_repeat1 = 35,
  aux_sym_code_block_repeat1 = 36,
  aux_sym__begin_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__inline_tag_false_positive] = "_inline_tag_false_positive",
  [sym_tag_name_with_argument] = "tag_name",
  [sym_tag_name_with_type] = "tag_name",
  [sym_tag_name] = "tag_name",
  [anon_sym_COLON] = ":",
  [anon_sym_SLASH] = "/",
  [anon_sym_DOT] = ".",
  [anon_sym_POUND] = "#",
  [anon_sym_TILDE] = "~",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [sym_code_block_language] = "code_block_language",
  [sym_code_block_line] = "code_block_line",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym__text] = "_text",
  [anon_sym_SLASH2] = "/",
  [anon_sym_STAR] = "*",
  [sym_type] = "type",
  [sym_document] = "document",
  [sym_description] = "description",
  [sym_tag] = "tag",
  [sym_inline_tag] = "inline_tag",
  [sym__expression] = "_expression",
  [sym_qualified_expression] = "qualified_expression",
  [sym_path_expression] = "path_expression",
  [sym_member_expression] = "member_expression",
  [sym_code_block] = "code_block",
  [sym_optional_identifier] = "optional_identifier",
  [sym__begin] = "_begin",
  [sym__end] = "_end",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
  [aux_sym_code_block_repeat1] = "code_block_repeat1",
  [aux_sym__begin_repeat1] = "_begin_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__inline_tag_false_positive] = sym__inline_tag_false_positive,
  [sym_tag_name_with_argument] = sym_tag_name,
  [sym_tag_name_with_type] = sym_tag_name,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [sym_code_block_language] = sym_code_block_language,
  [sym_code_block_line] = sym_code_block_line,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym__text] = sym__text,
  [anon_sym_SLASH2] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_type] = sym_type,
  [sym_document] = sym_document,
  [sym_description] = sym_description,
  [sym_tag] = sym_tag,
  [sym_inline_tag] = sym_inline_tag,
  [sym__expression] = sym__expression,
  [sym_qualified_expression] = sym_qualified_expression,
  [sym_path_expression] = sym_path_expression,
  [sym_member_expression] = sym_member_expression,
  [sym_code_block] = sym_code_block,
  [sym_optional_identifier] = sym_optional_identifier,
  [sym__begin] = sym__begin,
  [sym__end] = sym__end,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
  [aux_sym_code_block_repeat1] = aux_sym_code_block_repeat1,
  [aux_sym__begin_repeat1] = aux_sym__begin_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__inline_tag_false_positive] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_name_with_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name_with_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_code_block_language] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_qualified_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_path_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_optional_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__begin] = {
    .visible = false,
    .named = true,
  },
  [sym__end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__begin_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 7,
  [27] = 8,
  [28] = 9,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 19,
  [35] = 25,
  [36] = 21,
  [37] = 24,
  [38] = 38,
  [39] = 39,
  [40] = 38,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 41,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 46,
  [50] = 50,
  [51] = 47,
  [52] = 50,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 56,
  [67] = 67,
  [68] = 63,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(47);
      if (lookahead == '\n') SKIP(45);
      if (lookahead == '#') ADVANCE(161);
      if (lookahead == '.') ADVANCE(160);
      if (lookahead == '/') ADVANCE(159);
      if (lookahead == ':') ADVANCE(158);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '[') ADVANCE(190);
      if (lookahead == ']') ADVANCE(191);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '}') ADVANCE(50);
      if (lookahead == '~') ADVANCE(162);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(197);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '*') SKIP(1);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '[') ADVANCE(190);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(2);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(197);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '[') ADVANCE(190);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '}') ADVANCE(197);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '#') ADVANCE(161);
      if (lookahead == '*') SKIP(3);
      if (lookahead == '.') ADVANCE(160);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '~') ADVANCE(162);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(4);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != '~') ADVANCE(197);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '#') ADVANCE(161);
      if (lookahead == '.') ADVANCE(160);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '~') ADVANCE(162);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != '~') ADVANCE(197);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(5);
      if (lookahead == '#') ADVANCE(161);
      if (lookahead == '*') SKIP(5);
      if (lookahead == '.') ADVANCE(160);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == ':') ADVANCE(158);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '~') ADVANCE(162);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(7);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != '~') ADVANCE(197);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(5);
      if (lookahead == '#') ADVANCE(161);
      if (lookahead == '.') ADVANCE(160);
      if (lookahead == '/') ADVANCE(159);
      if (lookahead == ':') ADVANCE(158);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '~') ADVANCE(162);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != '~') ADVANCE(197);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(5);
      if (lookahead == '#') ADVANCE(161);
      if (lookahead == '.') ADVANCE(160);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == ':') ADVANCE(158);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '~') ADVANCE(162);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != '~') ADVANCE(197);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '*') SKIP(8);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(9);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(197);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '}') ADVANCE(197);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(11);
      if (lookahead == '*') ADVANCE(199);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(197);
      END_STATE();
    case 11:
      if (lookahead == '\n') SKIP(11);
      if (lookahead == '*') ADVANCE(200);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(11);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(10);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(197);
      END_STATE();
    case 12:
      if (lookahead == '\n') SKIP(12);
      if (lookahead == '*') SKIP(12);
      if (lookahead == '@') ADVANCE(40);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '}') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(13);
      if (lookahead != 0) ADVANCE(197);
      END_STATE();
    case 13:
      if (lookahead == '\n') SKIP(12);
      if (lookahead == '@') ADVANCE(40);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '}') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(197);
      END_STATE();
    case 14:
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '*') ADVANCE(178);
      if (lookahead == '`') ADVANCE(186);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(178);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(180);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(169);
      if (lookahead != 0) ADVANCE(182);
      END_STATE();
    case 15:
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '`') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(18);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(175);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '`') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(19);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(177);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 17:
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '`') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(21);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(168);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 18:
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '`') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(177);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '`') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(168);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 20:
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '`') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(175);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 21:
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '`') ADVANCE(186);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(180);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(169);
      if (lookahead != 0) ADVANCE(182);
      END_STATE();
    case 22:
      if (lookahead == '\n') SKIP(23);
      if (lookahead == '*') ADVANCE(179);
      if (lookahead == '`') ADVANCE(186);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(179);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(181);
      if (lookahead != 0) ADVANCE(182);
      END_STATE();
    case 23:
      if (lookahead == '\n') SKIP(23);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '`') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(27);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 24:
      if (lookahead == '\n') SKIP(23);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '`') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(28);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 25:
      if (lookahead == '\n') SKIP(23);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == '`') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(29);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == '\n') SKIP(23);
      if (lookahead == '`') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == '\n') SKIP(23);
      if (lookahead == '`') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == '\n') SKIP(23);
      if (lookahead == '`') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == '\n') SKIP(23);
      if (lookahead == '`') ADVANCE(186);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(181);
      if (lookahead != 0) ADVANCE(182);
      END_STATE();
    case 30:
      if (lookahead == '\n') SKIP(30);
      if (lookahead == '*') SKIP(30);
      if (lookahead == ']') ADVANCE(191);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(30);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(31);
      END_STATE();
    case 31:
      if (lookahead == '\n') SKIP(30);
      if (lookahead == ']') ADVANCE(191);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      END_STATE();
    case 32:
      if (lookahead == '\n') SKIP(32);
      if (lookahead == '*') SKIP(32);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(32);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(33);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(197);
      END_STATE();
    case 33:
      if (lookahead == '\n') SKIP(32);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(33);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '}') ADVANCE(197);
      END_STATE();
    case 34:
      if (lookahead == '*') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(34);
      END_STATE();
    case 35:
      if (lookahead == '`') ADVANCE(163);
      END_STATE();
    case 36:
      if (lookahead == '`') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(183);
      END_STATE();
    case 37:
      if (lookahead == '`') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(185);
      END_STATE();
    case 38:
      if (lookahead == '`') ADVANCE(35);
      END_STATE();
    case 39:
      ADVANCE_MAP(
        'a', 69,
        'b', 114,
        'c', 59,
        'e', 152,
        'f', 92,
        'i', 102,
        'm', 90,
        'n', 60,
        'p', 64,
        'r', 76,
        's', 61,
        't', 89,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 40:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 41:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(44);
      END_STATE();
    case 42:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(41);
      END_STATE();
    case 43:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(36);
      END_STATE();
    case 44:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(187);
      END_STATE();
    case 45:
      if (eof) ADVANCE(47);
      if (lookahead == '\n') SKIP(45);
      if (lookahead == '#') ADVANCE(161);
      if (lookahead == '*') SKIP(45);
      if (lookahead == '.') ADVANCE(160);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == ':') ADVANCE(158);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '[') ADVANCE(190);
      if (lookahead == ']') ADVANCE(191);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '}') ADVANCE(50);
      if (lookahead == '~') ADVANCE(162);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(45);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(170);
      if (lookahead != 0) ADVANCE(197);
      END_STATE();
    case 46:
      if (eof) ADVANCE(47);
      if (lookahead == '\n') SKIP(45);
      if (lookahead == '#') ADVANCE(161);
      if (lookahead == '.') ADVANCE(160);
      if (lookahead == '/') ADVANCE(198);
      if (lookahead == ':') ADVANCE(158);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '[') ADVANCE(190);
      if (lookahead == ']') ADVANCE(191);
      if (lookahead == '`') ADVANCE(196);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '}') ADVANCE(50);
      if (lookahead == '~') ADVANCE(162);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(197);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != '}') ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__inline_tag_false_positive);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__inline_tag_false_positive);
      if (lookahead == '}') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_tag_name_with_argument);
      if (lookahead == 'e') ADVANCE(134);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_tag_name_with_argument);
      if (lookahead == 's') ADVANCE(123);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_tag_name_with_argument);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_tag_name_with_type);
      if (lookahead == 'd') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_tag_name_with_type);
      if (lookahead == 's') ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_tag_name_with_type);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(101);
      if (lookahead == 'o') ADVANCE(107);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(145);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(103);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(135);
      if (lookahead == 'r') ADVANCE(117);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(137);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'b') ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(71);
      if (lookahead == 'l') ADVANCE(94);
      if (lookahead == 'p') ADVANCE(91);
      if (lookahead == 'u') ADVANCE(88);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(98);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(83);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(149);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(147);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'd') ADVANCE(137);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(143);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(108);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(111);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(141);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(137);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(113);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'f') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'f') ADVANCE(97);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'g') ADVANCE(105);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'h') ADVANCE(93);
      if (lookahead == 'y') ADVANCE(124);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(155);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(136);
      if (lookahead == 'u') ADVANCE(110);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(138);
      if (lookahead == 'r') ADVANCE(115);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(120);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(139);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'k') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'l') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'l') ADVANCE(68);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'l') ADVANCE(100);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'm') ADVANCE(126);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'm') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'm') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'm') ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(75);
      if (lookahead == 'r') ADVANCE(112);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(146);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(130);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(153);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(154);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(122);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(133);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(131);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(106);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(127);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'p') ADVANCE(53);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'p') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'p') ADVANCE(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'p') ADVANCE(118);
      if (lookahead == 't') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'p') ADVANCE(119);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(151);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(129);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(109);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(146);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 's') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 's') ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 's') ADVANCE(87);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 's') ADVANCE(148);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 's') ADVANCE(137);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(150);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(156);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(137);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(95);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(128);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'u') ADVANCE(132);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'u') ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'v') ADVANCE(82);
      if (lookahead == 'x') ADVANCE(125);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'w') ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'w') ADVANCE(137);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'x') ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'y') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_tag_name);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_code_block_language);
      if (lookahead == '`') ADVANCE(187);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(183);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_code_block_language);
      if (lookahead == '`') ADVANCE(187);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(184);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_code_block_language);
      if (lookahead == '`') ADVANCE(187);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(188);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_code_block_language);
      if (lookahead == '`') ADVANCE(187);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(189);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_code_block_language);
      if (lookahead == '`') ADVANCE(187);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(185);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_code_block_language);
      if (lookahead == '`') ADVANCE(187);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(182);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_code_block_language);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(170);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_code_block_language);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < '`' || 'z' < lookahead)) ADVANCE(42);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_code_block_language);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < '`' || 'z' < lookahead)) ADVANCE(37);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_code_block_language);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < '`' || 'z' < lookahead)) ADVANCE(44);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_code_block_language);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(177);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < '`' || 'z' < lookahead)) ADVANCE(43);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_code_block_language);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < '`' || 'z' < lookahead)) ADVANCE(41);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_code_block_language);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(187);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_code_block_language);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < '`' || 'z' < lookahead)) ADVANCE(36);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead == '*') ADVANCE(178);
      if (lookahead == '`') ADVANCE(186);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(178);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(180);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(169);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(182);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead == '*') ADVANCE(179);
      if (lookahead == '`') ADVANCE(186);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(179);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(181);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(182);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead == '`') ADVANCE(186);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(180);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(169);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(182);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead == '`') ADVANCE(186);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(181);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(182);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead == '`') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(182);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead == '`') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(189);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead == '`') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(188);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead == '`') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(184);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead == '`') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(42);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(37);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_code_block_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(43);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(192);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '*') ADVANCE(195);
      if (lookahead == '/') ADVANCE(194);
      if (lookahead == '`') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(194);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '*') ADVANCE(195);
      if (lookahead == '/') ADVANCE(194);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(194);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '*') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(34);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '/') ADVANCE(197);
      if (lookahead == '`') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(194);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '/') ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(194);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(anon_sym_SLASH2);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(200);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 33},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 13},
  [28] = {.lex_state = 13},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 13},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 20, .external_lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 20, .external_lex_state = 2},
  [46] = {.lex_state = 26, .external_lex_state = 2},
  [47] = {.lex_state = 26, .external_lex_state = 2},
  [48] = {.lex_state = 26, .external_lex_state = 2},
  [49] = {.lex_state = 26, .external_lex_state = 2},
  [50] = {.lex_state = 26, .external_lex_state = 2},
  [51] = {.lex_state = 26, .external_lex_state = 2},
  [52] = {.lex_state = 26, .external_lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 31},
  [60] = {.lex_state = 0, .external_lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 13},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0, .external_lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 13},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__inline_tag_false_positive] = ACTIONS(1),
    [sym_tag_name_with_argument] = ACTIONS(1),
    [sym_tag_name_with_type] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [sym_code_block_language] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym__text] = ACTIONS(1),
    [anon_sym_SLASH2] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(55),
    [sym__begin] = STATE(10),
    [anon_sym_SLASH2] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(17), 1,
      anon_sym_SLASH2,
    STATE(7), 1,
      sym_code_block,
    STATE(42), 1,
      sym_description,
    ACTIONS(7), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
    STATE(6), 5,
      sym__expression,
      sym_qualified_expression,
      sym_path_expression,
      sym_member_expression,
      sym_optional_identifier,
  [37] = 9,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(21), 1,
      anon_sym_SLASH2,
    STATE(7), 1,
      sym_code_block,
    STATE(39), 1,
      sym_description,
    ACTIONS(19), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
    STATE(4), 5,
      sym__expression,
      sym_qualified_expression,
      sym_path_expression,
      sym_member_expression,
      sym_optional_identifier,
  [71] = 7,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(27), 1,
      anon_sym_SLASH2,
    STATE(7), 1,
      sym_code_block,
    STATE(44), 1,
      sym_description,
    ACTIONS(23), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
    ACTIONS(25), 3,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_TILDE,
  [97] = 4,
    ACTIONS(31), 1,
      anon_sym_COLON,
    ACTIONS(33), 1,
      anon_sym_SLASH,
    ACTIONS(35), 4,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_TILDE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(29), 5,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
      anon_sym_SLASH2,
  [117] = 7,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(39), 1,
      anon_sym_SLASH2,
    STATE(7), 1,
      sym_code_block,
    STATE(43), 1,
      sym_description,
    ACTIONS(25), 3,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_TILDE,
    ACTIONS(37), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
  [143] = 7,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      sym__inline_tag_false_positive,
    ACTIONS(47), 1,
      sym__text,
    ACTIONS(49), 1,
      anon_sym_SLASH2,
    ACTIONS(45), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
    STATE(8), 3,
      sym_inline_tag,
      sym_code_block,
      aux_sym_description_repeat1,
  [169] = 7,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      sym__inline_tag_false_positive,
    ACTIONS(55), 1,
      sym__text,
    ACTIONS(57), 1,
      anon_sym_SLASH2,
    ACTIONS(53), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
    STATE(9), 3,
      sym_inline_tag,
      sym_code_block,
      aux_sym_description_repeat1,
  [195] = 7,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(62), 1,
      sym__inline_tag_false_positive,
    ACTIONS(67), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(70), 1,
      sym__text,
    ACTIONS(73), 1,
      anon_sym_SLASH2,
    ACTIONS(65), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
    STATE(9), 3,
      sym_inline_tag,
      sym_code_block,
      aux_sym_description_repeat1,
  [221] = 10,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(75), 1,
      sym_tag_name_with_argument,
    ACTIONS(77), 1,
      sym_tag_name_with_type,
    ACTIONS(79), 1,
      sym_tag_name,
    ACTIONS(81), 1,
      anon_sym_SLASH2,
    STATE(7), 1,
      sym_code_block,
    STATE(30), 1,
      sym_description,
    STATE(57), 1,
      sym__end,
    STATE(29), 2,
      sym_tag,
      aux_sym_document_repeat1,
  [253] = 3,
    ACTIONS(31), 1,
      anon_sym_COLON,
    ACTIONS(83), 4,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
    ACTIONS(85), 5,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_TILDE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_SLASH2,
  [270] = 2,
    ACTIONS(87), 4,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
    ACTIONS(89), 5,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_TILDE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_SLASH2,
  [284] = 2,
    ACTIONS(91), 4,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
    ACTIONS(93), 5,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_TILDE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_SLASH2,
  [298] = 2,
    ACTIONS(83), 4,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
    ACTIONS(85), 5,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_TILDE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_SLASH2,
  [312] = 7,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(17), 1,
      anon_sym_SLASH2,
    ACTIONS(95), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym_code_block,
    STATE(42), 1,
      sym_description,
    ACTIONS(7), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
  [336] = 2,
    ACTIONS(97), 4,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
    ACTIONS(99), 5,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_TILDE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_SLASH2,
  [350] = 3,
    ACTIONS(103), 1,
      anon_sym_STAR,
    STATE(22), 1,
      aux_sym__begin_repeat1,
    ACTIONS(101), 6,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym__text,
      anon_sym_SLASH2,
  [365] = 3,
    ACTIONS(107), 1,
      anon_sym_STAR,
    STATE(18), 1,
      aux_sym__begin_repeat1,
    ACTIONS(105), 6,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym__text,
      anon_sym_SLASH2,
  [380] = 2,
    ACTIONS(112), 3,
      sym__inline_tag_false_positive,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_SLASH2,
    ACTIONS(110), 5,
      anon_sym_LBRACE,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
  [393] = 6,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(17), 1,
      anon_sym_SLASH2,
    STATE(7), 1,
      sym_code_block,
    STATE(42), 1,
      sym_description,
    ACTIONS(7), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
  [414] = 2,
    ACTIONS(116), 3,
      sym__inline_tag_false_positive,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_SLASH2,
    ACTIONS(114), 5,
      anon_sym_LBRACE,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
  [427] = 3,
    ACTIONS(120), 1,
      anon_sym_STAR,
    STATE(18), 1,
      aux_sym__begin_repeat1,
    ACTIONS(118), 6,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym__text,
      anon_sym_SLASH2,
  [442] = 6,
    ACTIONS(9), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(21), 1,
      anon_sym_SLASH2,
    STATE(7), 1,
      sym_code_block,
    STATE(39), 1,
      sym_description,
    ACTIONS(19), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
  [463] = 2,
    ACTIONS(124), 3,
      sym__inline_tag_false_positive,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_SLASH2,
    ACTIONS(122), 5,
      anon_sym_LBRACE,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
  [476] = 2,
    ACTIONS(128), 3,
      sym__inline_tag_false_positive,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_SLASH2,
    ACTIONS(126), 5,
      anon_sym_LBRACE,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
      sym__text,
  [489] = 6,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(132), 1,
      sym__inline_tag_false_positive,
    ACTIONS(134), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(136), 1,
      sym__text,
    STATE(27), 3,
      sym_inline_tag,
      sym_code_block,
      aux_sym_description_repeat1,
  [510] = 6,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(134), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(138), 1,
      sym__inline_tag_false_positive,
    ACTIONS(140), 1,
      sym__text,
    STATE(28), 3,
      sym_inline_tag,
      sym_code_block,
      aux_sym_description_repeat1,
  [531] = 6,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    ACTIONS(145), 1,
      sym__inline_tag_false_positive,
    ACTIONS(148), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(151), 1,
      sym__text,
    STATE(28), 3,
      sym_inline_tag,
      sym_code_block,
      aux_sym_description_repeat1,
  [552] = 6,
    ACTIONS(75), 1,
      sym_tag_name_with_argument,
    ACTIONS(77), 1,
      sym_tag_name_with_type,
    ACTIONS(79), 1,
      sym_tag_name,
    ACTIONS(154), 1,
      anon_sym_SLASH2,
    STATE(67), 1,
      sym__end,
    STATE(33), 2,
      sym_tag,
      aux_sym_document_repeat1,
  [572] = 6,
    ACTIONS(75), 1,
      sym_tag_name_with_argument,
    ACTIONS(77), 1,
      sym_tag_name_with_type,
    ACTIONS(79), 1,
      sym_tag_name,
    ACTIONS(154), 1,
      anon_sym_SLASH2,
    STATE(67), 1,
      sym__end,
    STATE(31), 2,
      sym_tag,
      aux_sym_document_repeat1,
  [592] = 6,
    ACTIONS(75), 1,
      sym_tag_name_with_argument,
    ACTIONS(77), 1,
      sym_tag_name_with_type,
    ACTIONS(79), 1,
      sym_tag_name,
    ACTIONS(156), 1,
      anon_sym_SLASH2,
    STATE(61), 1,
      sym__end,
    STATE(33), 2,
      sym_tag,
      aux_sym_document_repeat1,
  [612] = 3,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_identifier,
    STATE(12), 5,
      sym__expression,
      sym_qualified_expression,
      sym_path_expression,
      sym_member_expression,
      sym_optional_identifier,
  [626] = 5,
    ACTIONS(158), 1,
      sym_tag_name_with_argument,
    ACTIONS(161), 1,
      sym_tag_name_with_type,
    ACTIONS(164), 1,
      sym_tag_name,
    ACTIONS(167), 1,
      anon_sym_SLASH2,
    STATE(33), 2,
      sym_tag,
      aux_sym_document_repeat1,
  [643] = 2,
    ACTIONS(110), 2,
      anon_sym_LBRACE,
      sym__text,
    ACTIONS(112), 3,
      anon_sym_RBRACE,
      sym__inline_tag_false_positive,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [653] = 2,
    ACTIONS(126), 2,
      anon_sym_LBRACE,
      sym__text,
    ACTIONS(128), 3,
      anon_sym_RBRACE,
      sym__inline_tag_false_positive,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [663] = 2,
    ACTIONS(114), 2,
      anon_sym_LBRACE,
      sym__text,
    ACTIONS(116), 3,
      anon_sym_RBRACE,
      sym__inline_tag_false_positive,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [673] = 2,
    ACTIONS(122), 2,
      anon_sym_LBRACE,
      sym__text,
    ACTIONS(124), 3,
      anon_sym_RBRACE,
      sym__inline_tag_false_positive,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [683] = 4,
    ACTIONS(134), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(169), 1,
      sym__text,
    STATE(26), 1,
      sym_code_block,
    STATE(66), 1,
      sym_description,
  [696] = 2,
    ACTIONS(27), 1,
      anon_sym_SLASH2,
    ACTIONS(23), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
  [705] = 4,
    ACTIONS(134), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(169), 1,
      sym__text,
    STATE(26), 1,
      sym_code_block,
    STATE(56), 1,
      sym_description,
  [718] = 4,
    ACTIONS(171), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(173), 1,
      sym_code_block_language,
    ACTIONS(175), 1,
      sym_code_block_line,
    STATE(50), 1,
      aux_sym_code_block_repeat1,
  [731] = 2,
    ACTIONS(39), 1,
      anon_sym_SLASH2,
    ACTIONS(37), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
  [740] = 2,
    ACTIONS(179), 1,
      anon_sym_SLASH2,
    ACTIONS(177), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
  [749] = 2,
    ACTIONS(183), 1,
      anon_sym_SLASH2,
    ACTIONS(181), 3,
      sym_tag_name_with_argument,
      sym_tag_name_with_type,
      sym_tag_name,
  [758] = 4,
    ACTIONS(185), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(187), 1,
      sym_code_block_language,
    ACTIONS(189), 1,
      sym_code_block_line,
    STATE(52), 1,
      aux_sym_code_block_repeat1,
  [771] = 3,
    ACTIONS(191), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(193), 1,
      sym_code_block_line,
    STATE(51), 1,
      aux_sym_code_block_repeat1,
  [781] = 3,
    ACTIONS(195), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(197), 1,
      sym_code_block_line,
    STATE(48), 1,
      aux_sym_code_block_repeat1,
  [791] = 3,
    ACTIONS(199), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(201), 1,
      sym_code_block_line,
    STATE(48), 1,
      aux_sym_code_block_repeat1,
  [801] = 3,
    ACTIONS(204), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(206), 1,
      sym_code_block_line,
    STATE(47), 1,
      aux_sym_code_block_repeat1,
  [811] = 3,
    ACTIONS(197), 1,
      sym_code_block_line,
    ACTIONS(204), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(48), 1,
      aux_sym_code_block_repeat1,
  [821] = 3,
    ACTIONS(197), 1,
      sym_code_block_line,
    ACTIONS(208), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(48), 1,
      aux_sym_code_block_repeat1,
  [831] = 3,
    ACTIONS(191), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(197), 1,
      sym_code_block_line,
    STATE(48), 1,
      aux_sym_code_block_repeat1,
  [841] = 2,
    ACTIONS(210), 1,
      sym_identifier,
    STATE(14), 1,
      sym_qualified_expression,
  [848] = 1,
    ACTIONS(212), 1,
      sym_identifier,
  [852] = 1,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
  [856] = 1,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
  [860] = 1,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
  [864] = 1,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
  [868] = 1,
    ACTIONS(222), 1,
      anon_sym_RBRACK,
  [872] = 1,
    ACTIONS(224), 1,
      sym_type,
  [876] = 1,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
  [880] = 1,
    ACTIONS(228), 1,
      sym_identifier,
  [884] = 1,
    ACTIONS(230), 1,
      sym_tag_name,
  [888] = 1,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
  [892] = 1,
    ACTIONS(234), 1,
      sym_type,
  [896] = 1,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
  [900] = 1,
    ACTIONS(238), 1,
      ts_builtin_sym_end,
  [904] = 1,
    ACTIONS(240), 1,
      sym_tag_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 71,
  [SMALL_STATE(5)] = 97,
  [SMALL_STATE(6)] = 117,
  [SMALL_STATE(7)] = 143,
  [SMALL_STATE(8)] = 169,
  [SMALL_STATE(9)] = 195,
  [SMALL_STATE(10)] = 221,
  [SMALL_STATE(11)] = 253,
  [SMALL_STATE(12)] = 270,
  [SMALL_STATE(13)] = 284,
  [SMALL_STATE(14)] = 298,
  [SMALL_STATE(15)] = 312,
  [SMALL_STATE(16)] = 336,
  [SMALL_STATE(17)] = 350,
  [SMALL_STATE(18)] = 365,
  [SMALL_STATE(19)] = 380,
  [SMALL_STATE(20)] = 393,
  [SMALL_STATE(21)] = 414,
  [SMALL_STATE(22)] = 427,
  [SMALL_STATE(23)] = 442,
  [SMALL_STATE(24)] = 463,
  [SMALL_STATE(25)] = 476,
  [SMALL_STATE(26)] = 489,
  [SMALL_STATE(27)] = 510,
  [SMALL_STATE(28)] = 531,
  [SMALL_STATE(29)] = 552,
  [SMALL_STATE(30)] = 572,
  [SMALL_STATE(31)] = 592,
  [SMALL_STATE(32)] = 612,
  [SMALL_STATE(33)] = 626,
  [SMALL_STATE(34)] = 643,
  [SMALL_STATE(35)] = 653,
  [SMALL_STATE(36)] = 663,
  [SMALL_STATE(37)] = 673,
  [SMALL_STATE(38)] = 683,
  [SMALL_STATE(39)] = 696,
  [SMALL_STATE(40)] = 705,
  [SMALL_STATE(41)] = 718,
  [SMALL_STATE(42)] = 731,
  [SMALL_STATE(43)] = 740,
  [SMALL_STATE(44)] = 749,
  [SMALL_STATE(45)] = 758,
  [SMALL_STATE(46)] = 771,
  [SMALL_STATE(47)] = 781,
  [SMALL_STATE(48)] = 791,
  [SMALL_STATE(49)] = 801,
  [SMALL_STATE(50)] = 811,
  [SMALL_STATE(51)] = 821,
  [SMALL_STATE(52)] = 831,
  [SMALL_STATE(53)] = 841,
  [SMALL_STATE(54)] = 848,
  [SMALL_STATE(55)] = 852,
  [SMALL_STATE(56)] = 856,
  [SMALL_STATE(57)] = 860,
  [SMALL_STATE(58)] = 864,
  [SMALL_STATE(59)] = 868,
  [SMALL_STATE(60)] = 872,
  [SMALL_STATE(61)] = 876,
  [SMALL_STATE(62)] = 880,
  [SMALL_STATE(63)] = 884,
  [SMALL_STATE(64)] = 888,
  [SMALL_STATE(65)] = 892,
  [SMALL_STATE(66)] = 896,
  [SMALL_STATE(67)] = 900,
  [SMALL_STATE(68)] = 904,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expression, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualified_expression, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_expression, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path_expression, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_expression, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optional_identifier, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_identifier, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__begin, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__begin_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__begin_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__begin, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_tag, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_tag, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 4, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_block_repeat1, 2, 0, 0),
  [201] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [214] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 4, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_type = 0,
  ts_external_token_code_block_line = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_type] = sym_type,
  [ts_external_token_code_block_line] = sym_code_block_line,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_type] = true,
  },
  [2] = {
    [ts_external_token_code_block_line] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_jsdoc_external_scanner_create(void);
void tree_sitter_jsdoc_external_scanner_destroy(void *);
bool tree_sitter_jsdoc_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_jsdoc_external_scanner_serialize(void *, char *);
void tree_sitter_jsdoc_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jsdoc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_jsdoc_external_scanner_create,
      tree_sitter_jsdoc_external_scanner_destroy,
      tree_sitter_jsdoc_external_scanner_scan,
      tree_sitter_jsdoc_external_scanner_serialize,
      tree_sitter_jsdoc_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "jsdoc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 23,
      .patch_version = 2,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
